### ISSUE TITLE
Did this work out for you?

### ISSUE THREAD

**Issue by NeoMatrixJR** [pk1057/veeam#1]
I'm also on unRAID and looking for a better backup solution... I've been using duplicati to backup my home computers to unraid and offsite to another linux computer (both running older Minio S3). and my unRAID offsite as well.  It's constantly having issues.  I've had a lot of suggestions to try Veeam (and I use it professionally for work...but not on linux).  If this worked for you, do you have an example template xml/config for your unraid setup?

**Comment by pk1057** [comment]
Hello,
it works nearly perfectly for me.
I use it on regulary daily base, but you need a windows vm with veem and this docker container, both with a internal resolvable ip address.

I backup all of my family pc's to a unraid volume and the  images will then be backed up to tape.
The container is updatable 
` <?xml version="1.0"?>
<Container version="2"> 
  <Name>veeam</Name>
  <Repository>pk1057/veeam</Repository>
  <Registry>https://hub.docker.com/r/pk1057/veeam/</Registry>
  <Network>br0</Network>
  <MyIP>192.168.178.19</MyIP>
  <Shell>sh</Shell>
  <Privileged>true</Privileged>
  <Support>https://hub.docker.com/r/pk1057/veeam/</Support>
  <Project/>
  <Overview>Backup of Linux Client in Container   Converted By Community Applications   Always verify this template (and values) against the dockerhub support page for the container</Overview>
  <Category/>
  <WebUI/>
  <TemplateURL/>
  <Icon>/plugins/dynamix.docker.manager/images/question.png</Icon>
  <ExtraParams>--hostname=veeam-linux.fritz.box</ExtraParams>
  <PostArgs/>
  <CPUset/>
  <DateInstalled>1626682164</DateInstalled>
  <DonateText/>
  <DonateLink/>
  <Description>Backup of Linux Client in Container   Converted By Community Applications   Always verify this template (and values) against the dockerhub support page for the container</Description>
  <Networking>
    <Mode>br0</Mode>
    <Publish/>
  </Networking>
  <Data>
    <Volume>
      <HostDir>/mnt/user</HostDir>
      <ContainerDir>/mnt</ContainerDir>
      <Mode>rw,shared</Mode>
    </Volume>
    <Volume>
      <HostDir>/mnt/cache/appdata/veeam</HostDir>
      <ContainerDir>/root/.ssh</ContainerDir>
      <Mode>rw</Mode>
    </Volume>
    <Volume>
      <HostDir>/mnt/cache/appdata/veeam/opt</HostDir>
      <ContainerDir>/opt/veeam</ContainerDir>
      <Mode>rw</Mode>
    </Volume>
  </Data>
  <Environment/>
  <Labels/>
  <Config Name="Data" Target="/mnt" Default="" Mode="rw,shared" Description="" Type="Path" Display="always" Required="false" Mask="false">/mnt/user</Config>
  <Config Name="SSH" Target="/root/.ssh" Default="" Mode="rw" Description="" Type="Path" Display="always" Required="false" Mask="false">/mnt/cache/appdata/veeam</Config>
  <Config Name="veeam data" Target="/opt/veeam" Default="" Mode="rw" Description="" Type="Path" Display="always" Required="false" Mask="false">/mnt/cache/appdata/veeam/opt</Config>
</Container>`
