### ISSUE TITLE
Can't get the Container to run

### ISSUE THREAD

**Issue by krjan02** [pk1057/veeam#2]
I can't get the container to run.

After starting the container no services are active, which also means that I have no access to the SSH server...

![image](https://github.com/pk1057/veeam/assets/26854748/ed3e0513-defa-4530-a963-b502b5d14e57)

Also im not able to start any services
![image](https://github.com/pk1057/veeam/assets/26854748/50c555cb-1ab1-4a6b-9674-355e23b38f87)

My Unraid version is the 6.12.0

**Comment by pk1057** [comment]
Two questions ?
Did you build the Container yourself or did you used my build Container for dockerhub pk1057/veeam:testing
Did you start IT in privileged mode because you need systems ?

**Comment by krjan02** [comment]
i used your build from dockerhub.
yes privileged mode was used.

I also tested it on another System (Debian 11 VM) it didn't work there either.

Here is my Config:
`<?xml version="1.0"?>
<Container version="2">
  <Name>veeam</Name>
  <Repository>pk1057/veeam</Repository>
  <Registry>https://hub.docker.com/r/pk1057/veeam/</Registry>
  <Network>br0</Network>
  <MyIP>192.168.178.19</MyIP>
  <Shell>sh</Shell>
  <Privileged>true</Privileged>
  <Support>https://hub.docker.com/r/pk1057/veeam/</Support>
  <Project/>
  <Overview>Backup of Linux Client in Container   Converted By Community Applications   Always verify this template (and values) against the dock>
  <Category/>
  <WebUI/>
  <TemplateURL/>
  <Icon>/plugins/dynamix.docker.manager/images/question.png</Icon>
  <ExtraParams>--hostname=veeam-linux.localdomain</ExtraParams>
  <PostArgs/>
  <CPUset/>
  <DateInstalled>1688311383</DateInstalled>
  <DonateText/>
  <DonateLink/>
  <Requires/>
  <Config Name="Data" Target="/mnt" Default="" Mode="rw,shared" Description="" Type="Path" Display="always" Required="false" Mask="false">/mnt/us>
  <Config Name="SSH" Target="/root/.ssh" Default="" Mode="rw" Description="" Type="Path" Display="always" Required="false" Mask="false">/mnt/cach>
  <Config Name="veeam data" Target="/opt/veeam" Default="" Mode="rw" Description="" Type="Path" Display="always" Required="false" Mask="false">/m>
</Container>`
Human Readable: https://p.jan.sx/?c75fe89c3ebbed48#FV6AuaZ6PyiaUDw8Kqr6xGhwbjha6NuM28MXYtFvPmvR

**Comment by pk1057** [comment]
Please pk1057/veeam:testing because this one is bases on newer.
Btw. i can't say if this version will work with 6.12 im currently running 6.11.5 and i need some days to test this against 6.12 could you please look at the thread in the unraid forum https://forums.unraid.net/topic/100983-backup-unraid-flash-with-veeam-backup-and-replication-server/#comment-1213618

**Comment by krjan02** [comment]
With the testing branch the container stops after starting:

This is the Log:
```
Synchronizing state of veeamservice.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable veeamservice
Synchronizing state of cron.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable cron
Check keygen
Check authorized keys
Check transport service
```

It seems like that "/usr/sbin/init" cannot be executed -->
```
Failed to create /init.scope control group: Read-only file system
Failed to allocate manager object: Read-only file system
[!!!!!!] Failed to allocate manager object.
Exiting PID 1...
```

**Comment by krjan02** [comment]
I was able to get it working (in a Debian 12 VM tho)

I had to mount the cgroups (/sys/fs/cgroup) as RW to the Container, aswell as use `--cgroupns host`

```
docker run -d \
  --name='veeam' \
  --net='br0.1337' \
  --ip='10.10.10.10' \
  --privileged=true \
  --cgroupns host \
  -e TZ="Europe/Berlin" \
  -v '/mnt/':'/mnt':'rw,shared' \
  -v '/sys/fs/cgroup':'/sys/fs/cgroup':'rw' \
  -v '/opt/veeam2':'/root/.ssh':'rw' \
  -v '/opt/veeam2/opt':'/opt/veeam':'rw' \
  --hostname=veeam.localdomain 'pk1057/veeam:testing'
```

There seems to be an issue with Unraid's cgroup mounting.
Im using it in an Debian 12 VM now since i dont want to expose Unraids cgroup as rw to the container.

**Comment by krjan02** [comment]
Now im facing issues with Veeam itself - Veeam can't find the mount point...

![image](https://github.com/pk1057/veeam/assets/26854748/dc4ae39f-8e1c-4b13-b3b7-8b2fcfc90225)

**Comment by pk1057** [comment]
This is my xml and also working with 6.12.2
Your xml on the top is the cgroup mount missing 

`<?xml version="1.0"?>
<Container version="2">
  <Name>veeam</Name>
  <Repository>pk1057/veeam:testing</Repository>
  <Registry/>
  <Network>br0</Network>
  <MyIP>XXX.XXX.XXX.XXX</MyIP>
  <Shell>sh</Shell>
  <Privileged>true</Privileged>
  <Support/>
  <Project/>
  <Overview/>
  <Category/>
  <WebUI/>
  <TemplateURL/>
  <Icon/>
  <ExtraParams> --tmpfs /tmp --tmpfs /run --tmpfs /run/lock --cgroupns=host</ExtraParams>
  <PostArgs/>
  <CPUset/>
  <DateInstalled>1674417465</DateInstalled>
  <DonateText/>
  <DonateLink/>
  <Requires/>
  <Config Name="/mnt/user" Target="/mnt" Default="/mnt/user" Mode="rw" Description="" Type="Path" Display="always" Required="false" Mask="false">/mnt/user</Config>
  <Config Name="/mnt/cache/appdata/veeam" Target="/root/.ssh" Default="" Mode="rw" Description="" Type="Path" Display="always" Required="false" Mask="false">/mnt/cache/appdata/veeam</Config>
  <Config Name="/mnt/cache/appdata/veeam/opt" Target="/mnt/user" Default="" Mode="rw" Description="" Type="Path" Display="always" Required="false" Mask="false">/mnt/cache/appdata/veeam/opt</Config>
  <Config Name="cgroup" Target="/sys/fs/cgroup" Default="" Mode="rw" Description="" Type="Path" Display="always" Required="false" Mask="false">/sys/fs/cgroup</Config>
</Container>
`
